# Generated by Django 5.1.3 on 2024-12-11 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, upload_to='photos/%y/%m/%d'),
        ),
    ]
